platform :ios, '13.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'SampleApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

    pod 'SocureDeviceRisk'
    pod 'SocureDocV'
end
