platform :ios, '12.0'

target 'SampleApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SocureSdkDemo
    pod 'SocureSdk', :git => 'https://github.com/socure-inc/socure-docv-sdk-ios', :branch=> '2.2.2'
end
