name: Security Scans

on:
  push:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  packages: read

jobs:
  security-scans:
    uses: commercial/common-ci-cd-workflows/.github/workflows/global-security-scans.yml@main
    with:
      team: docv
      service_name: docv-socure-docv-sdk-ios
      mend_product_name: socure-external
      enable_blackduck_scan: true
      enable_mend_scan: true
      enable_snyk_scan: true
      jdk_scan: true
      blackduck_strict_scan: false
      mend_strict_scan: false
      snyk_strict_scan: false
      detect_accuracy_required: NONE
      detect_tools: SIGNATURE_SCAN
    secrets: inherit
